global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "filebin-services"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "user-service:8080"
          - "file-service:8080"
          - "paste-service:8080"
          - "notification-service:8080"
          - "gateway:8080"

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "loki:3100"

  - job_name: "jaeger"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "jaeger:14269"