spring:
  application:
    name: paste-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/filebin-paste

server:
  port: 0

filebin:
  secret-key: ${FILEBIN_SECRET_KEY:NOIRS_FILEBIN_APPLICATION_IS_BEST_IN_THE_WORLD}

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "*"

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  file:
    name: /var/log/filebin/user-service.log
  pattern:
    console: "{ \"timestamp\": \"%d{yyyy-MM-dd HH:mm:ss}\", \"level\": \"%p\", \"service\": \"%X{spring.application.name}\", \"message\": \"%m\" }"
  level:
    ROOT: INFO

